WDS/WDS/Controllers/RetailerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using WDS.DAL.WdsEntities;
using WDS.Infrastructure.Services.ServiceInterfaces;
using WDS.ViewModels;
using WebGrease.Css.Ast;
using ClosedXML.Excel;
using System.IO;
using WDS.Models;

namespace WDS.Controllers
{
    public class RetailerController : Controller
    {
        private readonly IRetailerService _retailerService;
        private readonly IAuthService _authService;
        private readonly IDealerService _dealerService;
        private readonly IAdminService _adminService;
        private readonly IDashboardService _dashboardService;

        public RetailerController(IRetailerService retailerService, IAuthService authService, IDealerService dealerService, IAdminService adminService, IDashboardService dashboardService)
        {
            _retailerService = retailerService;
            _authService = authService;
            _dealerService = dealerService;
            _adminService = adminService;
            _dashboardService = dashboardService;
        }

        // GET: Retailer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RetailerOrder()
        {
            
            var order = new VmRetailerOrder();
            User user = null;
            if (HttpContext.Request.RequestContext.HttpContext.Session != null)
            {
                user = HttpContext.Request.RequestContext.HttpContext.Session["user"] as User;
                if (user != null)
                {
                    if (user.RoleId != null)
                    {
                        Role role = _authService.GetRoleById((long) user.RoleId);
                        if (role.RoleName.ToLower().Equals("retailer"))
                        {
                            RetailerInfo retailerInfo = _retailerService.GetRetailerInfoByPhoneNo(user.UserName);
                            order.RetailerId = retailerInfo.Id;
                            order.RetailerName = retailerInfo.RetailerName;

                            //tblDealerInfo dealer = _retailerService.GetDealerByCode(retailerInfo.DistributorCode);
                            //order.DealerCode = dealer.DealerCode;
                            //order.DealerName = dealer.DealerName;

                        }
                        else
                        {
                            return RedirectToAction("Login", "Auth", new { model = user });
                        }
                    }
                    else
                    {
                        return RedirectToAction("Logoff", "Auth");
                    }
                }
                else
                {
                    return RedirectToAction("Logoff", "Auth");
                }
            }
            else
            {
                return RedirectToAction("Logoff", "Auth");
            }
            List<SelectListItem> selectListItems = _retailerService.GetProductTypeListItems();
            ViewBag.ProductTypes = selectListItems;
            return View(order);
        }

        [HttpPost]
        public ActionResult RetailerOrder(VmRetailerOrder model)
        {
            if (model.RetailerOrderDetails.Any())
            {
                bool result = _retailerService.SaveRetailerOrder(model);
            }

            List<SelectListItem> selectListItems = _retailerService.GetProductTypeListItems();
            ViewBag.ProductTypes = selectListItems;
            return View(model);
        }
        public JsonResult GetModel(long phoneTypeId)
        {
            List<SelectListItem> modelItems = _retailerService.GetModelListItemByTypeId(phoneTypeId);
            return new JsonResult { Data = modelItems, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public ActionResult AddRow(long typeId, string model, int quantity)
        {
            var detail = new RetailerOrderDetail
            {
                ProductTypeId = typeId,
                Model = model, OrderQuantity = quantity
            };

            ModelPrice pricing = _retailerService.GetModelPrice(model);
            if (pricing != null)
            {
                detail.UnitPrice = pricing.Price;
                detail.OrderTotalPrice = quantity*detail.UnitPrice;
            }
            else
            {
                detail.UnitPrice = (decimal?) 0.0;
                detail.OrderTotalPrice = (decimal)0.0;
            }
            
            return PartialView("~/Views/Shared/_RetailerOrderDetail.cshtml", detail);
        }

        public ActionResult RetailerStockData()
        {
            if (HttpContext.Session != null)
            {
                User user = HttpContext.Session["user"] as User;
                if (user == null) return RedirectToAction("Logoff", "Auth");


                Role role = _adminService.GetRoleById(user.RoleId);
                List<Distributor> distributors = new List<Distributor>();
                if (role.RoleName.ToLower().Contains("admin") || role.RoleName.ToLower().Contains("management") ||
                    role.RoleName.ToLower().Contains("nsm") || role.RoleName.ToLower().Contains("rsm") ||
                    role.RoleName.ToLower().Contains("asm") || role.RoleName.ToLower().Contains("tso"))
                {
                    distributors = _dealerService.GetAllDistributors();
                    if (role.RoleName.ToLower().Contains("rsm") || role.RoleName.ToLower().Contains("asm") || role.RoleName.ToLower().Contains("tso"))
                    {
                        List<string> zoneNames = _dashboardService.GetRoleWiseZone(user.UserName);
                        distributors = distributors.Where(i => zoneNames.Contains(i.Zone)).ToList();
                    }

                }
                else
                {
                    distributors = _dealerService.GetAllDistributorByZone(user.UserName);
                }
                //List<Distributor> distributor = _retailerService.GetAllDistributorByZone(user.UserName);
                List<ProductMaster> productMaster = _retailerService.GetAllProductModels();
                List<SelectListItem> modelList = new List<SelectListItem>(){
                new SelectListItem
                {
                    Value = "0", Text = "--ALL--"
                }
                };
                List<SelectListItem> items = new List<SelectListItem>(){
                new SelectListItem
                {
                    Value = "0", Text = "--ALL--"
                }
                };
                items.AddRange(distributors.Select(m =>
                    new SelectListItem
                    {
                        Value = m.DigitechCode,
                        Text = m.DistributorNameCellCom
                    })
                );

                modelList.AddRange(productMaster.Select(m =>
                    new SelectListItem
                    {
                        Value = m.ProductModel,
                        Text = m.ProductModel
                    })
                );
                ViewBag.Dealers = items;
                ViewBag.modelList = modelList;
                ViewBag.retailerList = modelList;

                return View(new RetailerStockReportSearchBoxModel());
            }

            return RedirectToAction("Logoff", "Auth");
        }


        [HttpPost]
        public ActionResult RetailerStockData(RetailerStockReportSearchBoxModel model)//string fromDate, string toDate, string dealerCode, string modelName, long retailerId)
        {
            if (HttpContext.Session != null)
            {
                User user = HttpContext.Session["user"] as User;
                List<stp_retailer_sales_stock_Result> retailerSaleStockData = _retailerService.GetRetailerStockAndSaleData(model.StartDate.ToString(), model.EndDate.ToString(), model.DealerCode, model.ModelName, model.RetailerId, user);
                string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                string timeString = DateTime.Now.Year + "" + DateTime.Now.Month + "" + DateTime.Now.Day + "" + DateTime.Now.Hour + "" + DateTime.Now.Minute + "" + DateTime.Now.Second;
                string fileName = "RetailerStockData_"+ timeString +".xlsx";// + "_" + fromDate + "_" + toDate + ".xlsx";

                try
                {
                    using (var workBook = new XLWorkbook())
                    {
                        IXLWorksheet worksheet = workBook.Worksheets.Add("RetailerStockData");
                        worksheet.Columns("A", "Z").AdjustToContents();
                        worksheet.Cell("A1").Style.Font.SetBold().Font.FontSize = 10;
                        worksheet.Cell("A1").Value = "Dealer Name";

                        worksheet.Cell("B1").Style.Font.SetBold().Font.FontSize = 10;
                        worksheet.Cell("B1").Value = "Dealer Code";

                        worksheet.Cell("C1").Style.Font.SetBold().Font.FontSize = 10;
                        worksheet.Cell("C1").Value = "Retailer Name";

                        worksheet.Cell("D1").Style.Font.SetBold().Font.FontSize = 10;
                        worksheet.Cell("D1").Value = "Retailer Address";

                        worksheet.Cell("E1").Style.Font.SetBold().Font.FontSize = 10;
                        worksheet.Cell("E1").Value = "Phone No.";

                        worksheet.Cell("F1").Style.Font.SetBold().Font.FontSize = 10;
                        worksheet.Cell("F1").Value = "Model";

                        worksheet.Cell("G1").Style.Font.SetBold().Font.FontSize = 10;
                        worksheet.Cell("G1").Value = "Unit Price";

                        worksheet.Cell("H1").Style.Font.SetBold().Font.FontSize = 10;

WDS/WDS/Views/Retailer/RetailerOrder.cshtml
@using Antlr.Runtime
@model WDS.ViewModels.VmRetailerOrder
@{
    ViewBag.Title = "RetailerOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <div class="card-header">Create Order</div>
                <div class="card-body">
                    @using (Html.BeginForm("RetailerOrder", "Retailer", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model=>model.DealerCode)
                        @Html.HiddenFor(model=>model.DealerName)
                        @Html.HiddenFor(model=>model.RetailerId)
                        @Html.HiddenFor(model=>model.RetailerName)
                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label text-sm-right">Distributor Name</label>
                            <div class="col-lg-4">
                                @Html.TextBoxFor(model => model.DealerName, new { @class = "form-control" })
                            </div>
                            <label class="col-lg-2 col-form-label text-sm-right">Retailer Name</label>
                            <div class="col-lg-4">
                                @Html.TextBoxFor(model => model.RetailerName, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label text-sm-right">Product Type</label>
                            <div class="col-lg-4">
                                @Html.DropDownListFor(model => model.ProductTypeId, new SelectList(ViewBag.ProductTypes, "Value", "Text"), "Select", new
                                {
                                    @class = "selectpicker show-tick form-control", 
                                    data_live_search = "true",
                                    onchange = "LoadModel('"+@Url.Action("GetModel", "Retailer")+"')",
                                
                                })
                                @Html.ValidationMessageFor(model => model.ProductTypeId, "", new { @class = "text-danger" })
                            </div>
                            <label class="col-lg-2 col-form-label text-sm-right">Model</label>
                            <div class="col-lg-4">
                                @Html.DropDownListFor(m => m.ModelName, Enumerable.Empty<SelectListItem>(), "Please Select", new { @class = "selectpicker show-tick form-control", data_live_search = "true"})
                               
                                @Html.ValidationMessageFor(model => model.ModelName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            
                            <label class="col-lg-2 col-form-label text-sm-right">Quantity</label>
                            <div class="col-lg-4">
                                @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control", @type="number" })
                            </div>
                            <div class="col-lg-2"></div>
                            <div class="col-lg-4">
                                <button class="btn btn-outline-secondary" id="btnAdd">Add</button>
                                @*<input type="button" class="btn btn-outline-secondary" id="btnAdd" value="Add"/>*@
                            </div>
                        </div>
                        <div class="row">
                            <table class="table table-bordered" id="productTable">
                                <thead>
                                    <tr>
                                        <th>Model</th>
                                        <th>Quantity</th>
                                        <th>Unit Price</th>
                                        <th>Total</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody id="tcBody" class="tcBody">
                                    @if (Model.RetailerOrderDetails != null && Model.RetailerOrderDetails.Any())
                                    {
                                        foreach (var conditionModel in Model.RetailerOrderDetails)
                                        {
                                            Html.RenderPartial("~/Views/Shared/_RetailerOrderDetail.cshtml", conditionModel);
                                        }
                                    }
                                </tbody>
                            </table>

                        </div>
                        <div class="form-group row">

                            <div class="col-lg-8"></div>
                            <div class="col-lg-2">Grand Total</div>
                            <div class="col-lg-2">
                                @Html.TextBoxFor(i=>i.GrandTotal, new{@class="form-control"})
                            </div>
                        </div>
                        
                        <div class="form-group row">

                            
                            <div class="col-lg-2"></div>
                            <div class="col-lg-4">
                                @*<button class="btn btn-outline-secondary" id="btnAdd">Add</button>*@
                                <input type="submit" class="btn btn-outline-success" value="Submit"/>
                            </div>
                        </div>
                        

                    }

                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/CustomScripts/RetailerOrder.js"></script>

<script type="text/javascript">
    document.getElementById("btnAdd").addEventListener("click", function (event) {
        event.preventDefault();

        var url = '@Url.Action("AddRow", "Retailer")';
        var typeId = $('#ProductTypeId').val();
        var model = $('#ModelName').val();
        var quantity = $('#Quantity').val();
        $.post(url, { typeId: typeId, model: model, quantity: quantity }, function (data) {
            $('#tcBody').append(data);
            SumTotal();
        });
    });
    

    

</script>