WDS/WDS/Controllers/ManagementController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WDS.DAL.WdsEntities;
using WDS.Infrastructure.Services.ServiceInterfaces;
using WDS.ViewModels;

namespace WDS.Controllers
{
    public class ManagementController : Controller
    {
        private readonly IManagementService _managementService;

        public ManagementController(IManagementService managementService)
        {
            _managementService = managementService;
        }

        // GET: Management
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MarketShare()
        {
            List<Zone> zons = _managementService.GetZons();
            List<Brand> brands = _managementService.GetBrands();

            List<SelectListItem> zonsList = new List<SelectListItem> {
                new SelectListItem() {Value = "", Text = "--Select Zone--"},
            }; 
            zonsList.AddRange(zons.Select(i => new SelectListItem{
                        Text = i.ZoneName,
                        Value = i.Id.ToString()
                    })
            );
            ///////////////////////////////////////////

            List<SelectListItem> brandList = new List<SelectListItem> {
                new SelectListItem() {Value = "", Text = "--Select Brand--"},
            };
            brandList.AddRange(brands.Select(i => new SelectListItem
            {
                Text = i.BrandName,
                Value = i.Id.ToString()
            })
            );

            ViewBag.AllZoneList = zonsList;
            ViewBag.AllBrandList = brandList;

            return View();
        }
        [HttpPost]
        public ActionResult SaveMarketShareData(List<MarketShare> marketShareList)
        {
            if (HttpContext.Session != null)
            {
                if (marketShareList.Any())
                {
                    bool result = _managementService.SaveMarketShareData(marketShareList);

                    if (result)
                    {
                        var messageAndReload = new
                        {
                            m = result,
                            isRedirect = true,
                            MassageType = 1,
                            Message = "Saved successfully.",
                            redirectUrl = Url.Action("MarketShare")
                        };
                        return Json(messageAndReload, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        var messageAndReload = new
                        {
                            m = result,
                            isRedirect = false,
                            MassageType = 2,
                            Message = "Something went wrong!.",
                            redirectUrl = Url.Action("MarketShare")
                        };
                        return Json(messageAndReload, JsonRequestBehavior.AllowGet);
                    }

                }
            }
            return RedirectToAction("Logoff", "Auth");
       }
          [HttpPost]
        public ActionResult DubValueCheck(MarketShare objMarketShare)
        {
            bool result = _managementService.DubValueCheck(objMarketShare);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult AreaWiseTopBrandData(string period, string zone)
        {
            long zoneId = 0;
            long.TryParse(zone, out zoneId);

            int monthNo = 0;
            int yearNo = 0;

            if (!string.IsNullOrWhiteSpace(period))
            {
                var periodArr = period.Split(' ');
                monthNo = DateTime.ParseExact(periodArr[0], "MMMM", CultureInfo.InvariantCulture).Month; ;
                yearNo = 0;
                int.TryParse(periodArr[1], out yearNo);
            }

            List<stp_management_area_wise_top_brand_Result> data = _managementService.AreaWiseTopBrand(monthNo, yearNo, zoneId);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAreaWiseWaltonMarketShare(string period, string zone)
        {
            long zoneId = 0;
            long.TryParse(zone, out zoneId);

            int monthNo = 0;
            int yearNo = 0;

            if (!string.IsNullOrWhiteSpace(period))
            {
                var periodArr = period.Split(' ');
                monthNo = DateTime.ParseExact(periodArr[0], "MMMM", CultureInfo.InvariantCulture).Month; ;
                yearNo = 0;
                int.TryParse(periodArr[1], out yearNo);
            }

            List<stp_management_area_wise_market_share_Result> data = _managementService.GetAreaWiseWaltonMarketShare(monthNo, yearNo, zoneId);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAreaWisePieData(string period, string zone, string zoneTxt)
        {
            long zoneId = 0;
            long.TryParse(zone, out zoneId);

            int monthNo = 0;
            int yearNo = 0;

            if (!string.IsNullOrWhiteSpace(period))
            {
                var periodArr = period.Split(' ');
                monthNo = DateTime.ParseExact(periodArr[0], "MMMM", CultureInfo.InvariantCulture).Month; ;
                yearNo = 0;
                int.TryParse(periodArr[1], out yearNo);
            }
            

            List<stp_management_area_wise_market_share_walton_Result> data = _managementService.GetAreaWisePieData(monthNo, yearNo,zoneId);
            foreach (var ite in data)
            {
                if (ite.ZoneName== zoneTxt)
                {
                    ite.ZoneStatus = true; 
                }
            }

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetMarketSizeTilesData(string period, string zone)
        {
            long zoneId = 0;
            long.TryParse(zone, out zoneId);

            int monthNo = 0;
            int yearNo = 0;

            if (!string.IsNullOrWhiteSpace(period))
            {
                var periodArr = period.Split(' ');
                monthNo = DateTime.ParseExact(periodArr[0], "MMMM", CultureInfo.InvariantCulture).Month; ;
                yearNo = 0;
                int.TryParse(periodArr[1], out yearNo);
            }


            List<stp_market_size_Result> data = _managementService.GetMarketSizeTile(monthNo, yearNo, zoneId);
            return Json(data, JsonRequestBehavior.AllowGet);
        }




        public ActionResult RetailerInformations()
        {
            List<Zone> zons = _managementService.GetZons();

            List<SelectListItem> zonsList = new List<SelectListItem> {
                new SelectListItem() {Value = "", Text = "--Select Zone--"},
            };
            zonsList.AddRange(zons.Select(i => new SelectListItem
                {
                    Text = i.ZoneName,
                    Value = i.Id.ToString()
                })
            );
            ViewBag.AllZoneList = zonsList;
            return View();
        }

        public ActionResult GetRetailerCount(string zone)
        {
            long zoneId = 0;
            long.TryParse(zone, out zoneId);

            

            List<stp_management_retailer_count_Result> data = _managementService.GetRetailerCount(zoneId);

            if (data.Any())
            {
                stp_management_retailer_count_Result result = data.FirstOrDefault();
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return Json(null, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetRetailers(string zone)
        {
            long zoneId = 0;
            long.TryParse(zone, out zoneId);



            List<stp_management_retailer_list_zone_Result> data = _managementService.GetRetailers(zoneId);
            return new JsonResult()
            {
                Data = data,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
    }
}

WDS/WDS/Views/Management/MarketShare.cshtml
@{
    ViewBag.Title = "MarketShare";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .ui-datepicker-calendar {
        display: none;
    }
</style>
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header">Create New</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label text-sm-right">Priod</label>
                            <div class="col-lg-6">
                                <input class="form-control datepicker" id="Priod" readonly>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label text-sm-right">Zone</label>
                            <div class="col-lg-6">
                                @Html.DropDownList("Zone", ViewBag.AllZoneList as List<SelectListItem>, new { @class = "selectpicker show-tick form-control", data_live_search = "true", id = "zone" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        @*<div class="form-group row">
                            <label class="col-lg-3 col-form-label text-sm-right">Year</label>
                            <div class="col-lg-6">
                                <input class="form-control datepicker" id="year" readonly>
                            </div>
                        </div>*@
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label text-sm-right">Brand</label>
                            <div class="col-lg-6">
                                @Html.DropDownList("Brand", ViewBag.AllBrandList as List<SelectListItem>, new { @class = "selectpicker show-tick form-control", data_live_search = "true", id = "brand" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label text-sm-right">Market Share Amt.</label>
                            <div class="col-lg-6">
                                <input class="form-control" id="shareAmount" type="number">
                            </div>
                        </div>
                    </div>
                </div>
               


                <div class="form-group row">
                    <div class="col-lg-3"></div>
                    <div class="col-lg-6">
                        <input type="button" value="Add Now" id="addNow" class="btn btn-outline-success">
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header"><input type="button" value="SaveAll" id="saveAll" class="btn btn-outline-success"></div>
            <div class="card-body">
                <div class="row">
                    <table class="table table-striped table-scrollable table-bordered table-hover dtTable first" id="marketShareAppandTable">
                        <thead>
                            <tr>
                                <th>Month</th>
                                <th>Year</th>
                                <th>Zone</th>
                                <th>Brand</th>
                                <th>Share Amt.</th>
                            </tr>
                        </thead>
                        <tbody id="marketShareAppandTableBody"></tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
<link href="~/Content/iziToast.min.css" rel="stylesheet" />
<script src="~/Scripts/iziToast.min.js"></script>
<script>
    $(document).ready(function () {
        $("#Priod").datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'MM yy',
            onClose: function (dateText, inst) {
                $(this).datepicker('setDate', new Date(inst.selectedYear, inst.selectedMonth, 1));
            }
        });
        //$("#year").datepicker({
        //    //changeMonth: true,
        //    changeYear: true,
        //    showButtonPanel: true,
        //    dateFormat: 'yy',
        //    onClose: function (dateText, inst) {
        //        $(this).datepicker('setDate', new Date(inst.selectedYear, inst.selectedMonth, 1));
        //    }
        //});
        
        $("#addNow").click(function () {

            var Priod = $("#Priod").val();
            var dformate = new Date(Priod);
            var monthNumber = dformate.getMonth() + 1;
            var month = Priod.split(' ')[0];
            var year = Priod.split(' ')[1];
            var zoneId = $("#zone").val();
            var brandId = $("#brand").val();
            var zonetext = $("#zone option:selected").text();
            var brandext = $("#brand option:selected").text();
            var shareAmount = $("#shareAmount").val();
            if (validation()) {
                var objData = {
                    'ZoneId': zoneId,
                    'BrandId': brandId,
                    'MonthName': month,
                    'YearNumber': year,
                    'ShareAmount': shareAmount,
                }
                var dataList = JSON.stringify({ objMarketShare: objData });
                $.ajax({
                    type: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    url: '@Url.Action("DubValueCheck", "Management")',
                    data: dataList,
                    success: function (data) {
                        if (data) { // Check With Database
                            iziToast.error({
                                title: 'Error',
                                position: 'center',
                                message: 'This Data IS Already Exist in Database!.',
                            });
                        } else {
                            var dupcount = 0;
                            var TablerowCount = $('#marketShareAppandTableBody tr').length;
                            if (TablerowCount > 0) {
                            $.each($("#marketShareAppandTableBody tr"), function () {
                                MoNameV= $(this).find('td:eq(1)').html();
                                YeNumberV= $(this).find('td:eq(2)').html();
                                zoneV= $(this).find('td:eq(3)').html();
                                brandV = $(this).find('td:eq(4)').html();
                                if (MoNameV == month && YeNumberV == year && zoneV == zoneId && brandV == brandId) {//Chack With Appand Table
                                    dupcount += 1;
                                    iziToast.error({
                                        title: 'Error',
                                        position: 'center',
                                        message: 'Already Added!.',
                                    });


                                } 
                            });

                            if (dupcount==0) {
                                tableAppand(monthNumber, month, year, zoneId, brandId, zonetext, brandext, shareAmount);
                            }
                           
                            } else {
                                tableAppand(monthNumber, month, year, zoneId, brandId, zonetext, brandext, shareAmount);
                            }
                        }
                    }
                });



            }
           

        });
        $("#saveAll").click(function () {
            var allDataInfo = [];
            allDataInfo.length = 0;
            $.each($("#marketShareAppandTableBody tr"),
               function () {
                   allDataInfo.push({
                       MonthNumber: $(this).find('td:eq(0)').html(),
                       MonthName: $(this).find('td:eq(1)').html(),
                       YearNumber: $(this).find('td:eq(2)').html(),
                       ZoneId: $(this).find('td:eq(3)').html(),
                       BrandId: $(this).find('td:eq(4)').html(),
                       ShareAmount: $(this).find('td:eq(7)').html(),
                      
                   });

               });
            if (allDataInfo.length > 0) {
                var dataList = JSON.stringify({ marketShareList: allDataInfo });
                $.ajax({
                    type: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    url: '@Url.Action("SaveMarketShareData", "Management")',
                    data: dataList,
                    success: function(data) {
                        if (data.isRedirect && data.m) {
                            window.setTimeout(function() {
                                window.location = data.redirectUrl;
                            }, 1000);
                            iziToast.success({
                                title: 'Success',
                                position: 'center',
                                message: data.Message,
                            });
                        } else {
                            iziToast.error({
                                title: 'Error',
                                position: 'center',
                                message: data.Message,
                            });
                        }
                    }
                });
            } else {
                iziToast.error({
                    title: 'Error',
                    position: 'center',
                    message: 'Table Data Must Select!.',
                });
            }
        });
        });



 
    function reset() {
        //$("#Priod").val("");
        $("#zone").val("");
       $("#brand").val("");
       //$("#brand option:selected").empty();
       $("#shareAmount").val("");

       var xB = document.getElementById("brand");
      // xB.querySelector("div.filter-option > div.filter-option-inner > div:first-child").innerHTML = 'dsfds';
       $("div.filter-option > div.filter-option-inner > div:first-child").text("--Select--");
    }
    function validation() {
        var month = $("#month").val();
        if (month == "") {
            iziToast.error({
                title: 'error',
                position: 'center',
                message: 'select month',
            });
            return false;
        }
        
        var zoneId = $("#zone").val();
        if (zoneId == "") {
            iziToast.error({
                title: 'error',
                position: 'center',
                message: 'select Zone',
            });
            return false;
        }
        var brandId = $("#brand").val();
        if (brandId == "") {
            iziToast.error({
                title: 'error',
                position: 'center',
                message: 'select Brand ',
            });
            return false;
        }
        var shareAmount = $("#shareAmount").val();
        if (shareAmount == "") {
            iziToast.error({
                title: 'error',
                position: 'center',
                message: 'Enter Amount',
            });
            return false;
        }
        return true;
    }



    function tableAppand(monthNumber, month, year, zoneId, brandId, zonetext, brandext, shareAmount) {
            $("#marketShareAppandTableBody").append('<tr>' +
                    '<td style="display:none;">' +
                    monthNumber +
                    '</td>' +
                    '<td>' +
                    month +
                    '</td>' +
                    '<td>' +
                    year +
                    '</td>' +
                    '<td style="display:none;">' +
                    zoneId +
                    '</td>' +
                    '<td style="display:none;">' +
                    brandId +
                    '</td>' +
                    '<td>' +
                    zonetext +
                    '</td>' +
                    '<td>' +
                    brandext +
                    '</td>' +
                    '<td>' +
                    shareAmount +
                    '</td>' +
                    '</tr>');
                    reset();
    }
    
</script>

WDS/WDS/Views/Management/RetailerInformations.cshtml
@{
    ViewBag.Title = "RetailerInformations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <div class="row">
                    @*<div class="col-md-4">
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label text-sm-right">Priod</label>
                            <div class="col-lg-6">
                                <input class="form-control datepicker" id="Priod" readonly>
                            </div>
                        </div>
                    </div>*@
                    <div class="col-md-4">
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label text-sm-right">Zone</label>
                            <div class="col-lg-6">
                                @Html.DropDownList("Zone", ViewBag.AllZoneList as List<SelectListItem>, new { @class = "selectpicker show-tick form-control", data_live_search = "true", id = "zone" })
                            </div>
                        </div>
                    </div>
                    @*<div class="col-md-4">

                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label text-sm-right">Brand</label>
                            <div class="col-lg-6">
                                @Html.DropDownList("Brand", ViewBag.AllBrandList as List<SelectListItem>, new {@class = "selectpicker show-tick form-control", data_live_search = "true", id = "brand"})
                            </div>
                            <button class="btn btn-default" id="btnSubmit">Search</button>
                        </div>

                    </div>*@
                </div>
                <hr />
                <div class="row">

                    <div class="col-md-6">
                        <div class="card" style="border-radius: 20px; background-color:whitesmoke">
                            <div class="card-body">
                                <div class="rotate">
                                    <div>
                                        <h2 id="wRetailers">0</h2>
                                    </div>
                                </div>
                                <h4 class="text-uppercase text-right">All Retailers</h4>

                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card" style="border-radius: 20px; background-color:whitesmoke">
                            <div class="card-body">
                                <div>
                                    <h2 id="oRetailers">0</h2>
                                </div>
                                <h4 class="text-uppercase text-right">Walton Retailers</h4>

                            </div>
                        </div>
                    </div>

                </div>
                <table class="table table-bordered" id="tblRetailers">
                    <thead>
                    <tr>
                        <th>Retailer Name</th>
                        <th>Phone</th>
                        <th>Distributor Code</th>
                        <th>Distributor Name</th>
                    </tr>
                    </thead>
                    <tbody id="tcBody"></tbody>
                </table>
                
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">
    $(function () {
        $("#tblRetailers").DataTable();

        GetRetailerCount('');
        GetRetailers('');

        $('#zone').on('change', function() {
            var zone = $(this).val();
            GetRetailerCount(zone);
            GetRetailers(zone);
        });
    });

    function GetRetailerCount(zone) {
        $.ajax({
            type: 'POST',

            url: '@Url.Action("GetRetailerCount", "Management")',
            dataType: 'json',
            data: { zone: zone },
            success: function (data) {
                if (data!=null) {
                    $('#wRetailers').html(data.AllRetailer);
                    $('#oRetailers').html(data.WaltonRetailer);
                } else {
                    $('#wRetailers').html('No Data Found');
                    $('#oRetailers').html('No Data Found');
                }

            }
        });
    }


    function GetRetailers(zone) {
        $.ajax({
            type: 'POST',

            url: '@Url.Action("GetRetailers", "Management")',
            dataType: 'json',
            data: { zone: zone },
            success: function (data) {
                $('#tblRetailers').DataTable().destroy();
                $("#tcBody").html("");
                if (data.length > 0) {
                    $('#tblRetailers').DataTable().destroy();
                    $("#tcBody").html("");

                    var dataList = data.length;

                    for (var i = 0; i < dataList; i++) {
                        $("#tcBody").append('<tr>' +
                            '<td>' + data[i].RetailerName + '</td>' +
                            '<td>' + data[i].PhoneNumber + '</td>' +
                            '<td>' + data[i].DistributorCode + '</td>' +
                            '<td>' + data[i].DistributorName + '</td>' +
                            '</tr>');

                    }
                    var table = $('#tblRetailers').DataTable();

                    new $.fn.dataTable.Buttons(table, {
                        buttons: [
                            { extend: 'excel', className: 'excelBtn', title: 'Sales Report', text: 'Click For Excel Export' }
                        ]
                    });

                    table.buttons(0, null).container().prependTo(
                        table.table().container()
                    );
                }
            }
        });
    }
</script>